insert into tb_user (name, email, password) values ('Bob Bronw','bob@gmail.com','$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
insert into tb_user (name, email, password) values ('Ana White','ana@gmail.com','$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

insert into tb_role (authority) values ('VISITOR');
insert into tb_role (authority) values ('MEMBER');

insert into tb_movie (title,sub_title,year,img_url,synopisis) values ('Mortal Kombat','Get over here.',2021,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg','Nova aventura baseada no videogame Mortal Kombat. Na história, um jovem que nunca treinou artes marciais acaba envolvido em um gigantesco torneio de luta envolvendo guerreiros da Terra e lutadores e outras dimensões.');
insert into tb_movie (title,sub_title,year,img_url,synopisis) values ('Bad Boys Para Sempre','Sempre juntos. Até o final.',2020,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/upUy2QhMZEmtypPW3PdieKLAHxh.jpg','Armando é um assassino de sangue frio com uma natureza cruel e provocadora. Ele está comprometido com o trabalho do cartel e é enviado por sua mãe para matar Mike (Smith). Nuñez assumirá o papel de Rita, psicóloga criminal durona e engraçada que é recém-nomeada chefe da AMMO e é ex-namorada de Mike.');
insert into tb_movie (title,sub_title,year,img_url,synopisis) values ('Sem Remorso','Sem Remorso.',2021,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/qV7HOOZvBLYnjQpSWIVl7mQiAjx.jpg','Um agente da CIA busca vingança depois de sua namorada ter sido morta por um traficante de Baltimore.');
insert into tb_movie (title,sub_title,year,img_url,synopisis) values ('Godzilla vs. Kong','Um dos dois cairá.',2021,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg','Em uma época em que os monstros andam na Terra, a luta da humanidade por seu futuro coloca Godzilla e Kong em rota de colisão que verá as duas forças mais poderosas da natureza no planeta se confrontarem em uma batalha espetacular para as idades. Enquanto Monarch embarca em uma missão perigosa em terreno desconhecido e descobre pistas sobre as origens dos Titãs, uma conspiração humana ameaça tirar as criaturas, boas e más, da face da terra para sempre.');
insert into tb_movie (title,sub_title,year,img_url,synopisis) values ('Anônimo','Nunca subestime um anônimo.',2021,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/83Hp44xD24OndqfaJbXFQqD25EX.jpg','Quando dois ladrões invadem sua casa no subúrbio uma noite, Hutch se recusa a defender a si mesmo ou a sua família, na esperança de evitar violência grave. Seu filho adolescente, Blake, está desapontado com ele e sua esposa, Becca, parece se afastar ainda mais. Em consequência, o incidente acerta a raiva latente de Hutch, desencadeando instintos adormecidos e impulsionando-o em um caminho brutal que revelará segredos obscuros e habilidades letais para salvar sua família.');
insert into tb_movie (title,sub_title,year,img_url,synopisis) values ('Liga da Justiça de Zack Snyder','Caído. Ressuscitado. Unidos.',2021,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/pcDc2WJAYGJTTvRSEIpRZwM3Ola.jpg','Determinado a garantir que o sacrifício final do Superman não foi em vão, Bruce Wayne alinha forças com Diana Prince com planos de recrutar uma equipe de metahumanos para proteger o mundo de uma ameaça de proporções catastróficas que se aproxima.');
insert into tb_movie (title,sub_title,year,img_url,synopisis) values ('Monster Hunter','Junte-se à caçada.',2020,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/z8TvnEVRenMSTemxYZwLGqFofgF.jpg','Baseado no jogo da Capcom chamado Monster Hunter, a tenente Artemis e seus soldados são transportados para um novo mundo. Lá, eles se envolvem em batalhas imponentes, buscando desesperadamente a sobrevivência contra bestas gigantes portadoras de habilidades surreais.');
insert into tb_movie (title,sub_title,year,img_url,synopisis) values ('Zona de Combate','Defiant by design.',2021,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/lOSdUkGQmbAl5JQ3QoHqBZUbZhC.jpg','Em um futuro próximo, um piloto de drone e um androide ultrassecreto trabalham lado a lado no campo de batalha para evitar um ataque nuclear.');
insert into tb_movie (title,sub_title,year,img_url,synopisis) values ('Sociedade da Justiça: 2ª Guerra Mundial','The fight for justice is the greatest battle of all time.',2021,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hcVvlb1Ei1zYUGoiv3fp3fWonqt.jpg','A viagem relaxante de Barry Allen para Metrópolis está prestes a dar errado. Enquanto corre para ajudar em uma luta inesperada, o Flash rompe as barreiras do tempo, e acaba parando no meio da Segunda Guerra Mundial. É lá que o Flash conhece a Mulher Maravilha e a equipe supersecreta dela, conhecida como Sociedade da Justiça da América. Testemunhe os rumos turbulentos da guerra, combates envolventes e a velocidade da honra enquanto o Flash luta para voltar ao seu próprio tempo!');
insert into tb_movie (title,sub_title,year,img_url,synopisis) values ('Jiu Jitsu','From the darkness, the ultimate fighter rises.',2020,'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jeAQdDX9nguP6YOX6QSWKDPkbBo.jpg','Uma antiga ordem de experientes lutadores de Jiu Jitsu enfrenta temíveis invasores alienígenas em uma batalha pela Terra a cada seis anos.');

insert into tb_genre (name) values ('Ação');
insert into tb_genre (name) values ('Fantasia');
insert into tb_genre (name) values ('Ficção científica');

